# Generated by Django 6.0.2 on 2026-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='fat',
            new_name='fats',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='food',
            name='saturated_fat',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fats',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
