# Generated by Django 6.0.2 on 2026-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_fat_food_fats_remove_food_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
